### ISSUE TITLE
delete resource error

### ISSUE THREAD

**Issue by cjen07** [tony612/qiniu#10]
[error] #PID<0.722.0> running DoScience.Web.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/editor/delete_image
** (exit) an exception was raised:
    ** (Poison.SyntaxError) Unexpected end of input at position 0
        (poison) lib/poison/parser.ex:55: Poison.Parser.parse!/2
        (poison) lib/poison.ex:83: Poison.decode!/2
        (qiniu) lib/qiniu/http.ex:34: Qiniu.HTTP.request/4
        (do_science) lib/do_science/web/controllers/editor_controller.ex:120: DoScience.Web.EditorController.delete_image/2
        (do_science) lib/do_science/web/controllers/editor_controller.ex:1: DoScience.Web.EditorController.action/2
        (do_science) lib/do_science/web/controllers/editor_controller.ex:1: DoScience.Web.EditorController.phoenix_controller_pipeline/2
        (do_science) lib/do_science/web/endpoint.ex:1: DoScience.Web.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
        (do_science) lib/do_science/web/endpoint.ex:1: DoScience.Web.Endpoint.plug_builder_call/2
        (do_science) lib/plug/debugger.ex:123: DoScience.Web.Endpoint."call (overridable 3)"/2
        (do_science) lib/do_science/web/endpoint.ex:1: DoScience.Web.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/cjen/Documents/do_science/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

and the response in request in Qiniu.HTTP is

[debug] %HTTPoison.Response{body: "", headers: [{"Server", "openresty"}, {"Date", "Tue, 18 Apr 2017 09:40:53 GMT"}, {"Content-Type", "application/json"}, {"Content-Length", "0"}, {"Connection", "close"}, {"X-Log", "RA:101.71.81.88:80;rs9_3.sel:3;rs9_3.sel;rs9_3.ups;rwro.rm:4;MQ;mc.d;RS:7;ZONEPROXY:44;NUPROXY:64"}, {"X-Reqid", "YEEAAJN4Cd2HdLYU"}, {"X-Reqid", "YEEAAJN4Cd2HdLYU"}, {"X-Reqid", "YEEAAJN4Cd2HdLYU"}], status_code: 200}

**Comment by cjen07** [comment]
@tony612 

should it be 

```elixir
if opts[:raw] || response.body == "" do
   response
else
   %{response | body: Poison.decode!(response.body)}
end
```

in http.ex

**Comment by cjen07** [comment]
the above approach fixed my problem

**Comment by tony612** [comment]
@cjen07 Your problem should be fixed by https://hex.pm/packages/qiniu/0.3.5

Thanks!

**Comment by cjen07** [comment]
Yes :+1:
