### ISSUE TITLE
How to get parsed resp body by Qiniu.Uploader.upload

### ISSUE THREAD

**Issue by goofansu** [tony612/qiniu#5]
The body is not parsed by Poison: `{\"hash\":\"FnQywUlnZVbpMYJGPKVUpZeUVTiw\",\"key\":\"test.mp4\"}`

I looked at the source code, found that the `opts` are not passed to `Qiniu.HTTP.post/3`

**Comment by goofansu** [comment]
Thanks

**Comment by tony612** [comment]
@goofansu 0.3.3 is released with this fix

**Comment by goofansu** [comment]
Great, I'll upgrade deps :)
