### ISSUE TITLE
The qiniu is not an OTP application

### ISSUE THREAD

**Issue by xingxing** [tony612/qiniu#7]
Hi Tony, as titled. Please correct the README file.  Thanks a lot.

**Comment by xingxing** [comment]
Oh, My bad, you added `qiniu` to applications for starting HTTPosion?

**Comment by tony612** [comment]
Yes. btw, even non-OTP can be an application -- library application and can be added to applications. See 1.3 of http://erlang.org/doc/design_principles/des_princ.html or the last section of http://learnyousomeerlang.com/building-otp-applications
